routes/admin.php
<?php

use App\Http\Controllers\ChangeLocalizationAction;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\LocalizationMiddleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([ 'middleware' => LocalizationMiddleware::class], function () {

    Route::resource('users', UserController::class);
    Route::resource('Roles', RoleController::class);
//    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

routes/user.php
<?php

use App\Http\Controllers\ChangeLocalizationAction;
use App\Http\Controllers\UserController;
use App\Http\Middleware\LocalizationMiddleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/user-home', [App\Http\Controllers\HomeController::class, 'user_index'])->name('user.home');

routes/web.php
<?php

use App\Http\Controllers\ChangeLocalizationAction;
use App\Http\Controllers\UserController;
use App\Http\Middleware\LocalizationMiddleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('change-language/{locale}', [ChangeLocalizationAction::class, '__invoke'])
    ->name('change-language');

Route::group([ 'middleware' => LocalizationMiddleware::class], function () {
        // Routes for administrators
    Route::prefix('admin')->middleware('admin')->group(function () {
        require __DIR__ . '/admin.php';
    });

    // Routes for clients
    Route::middleware('auth')->group(function () {
        require __DIR__ . '/user.php';
    });

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class,'logout']);
    Auth::routes();

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::get('/show-profile', [App\Http\Controllers\UserController::class, 'user_profile'])->name('show_profile');
    Route::PUT('/update-profile/{user}', [App\Http\Controllers\UserController::class, 'update_user_profile'])->name('update_profile');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $fillable = ['name'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if(!auth()->user()->hasPermission('permission_index') && auth()->user()->id != "1"){
             abort(404);
        }
        $roles = Role::all();
        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        if(!auth()->user()->hasPermission('permission_create') && auth()->user()->id != "1"){
            abort(404);
        }
        $permissions = $permissions = Permission::select('model_name')->distinct()->pluck('model_name');
        return view('roles.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required|unique:roles,name',
            'permissions' => 'array',
        ]);
        $role = Role::create($validate);
        $role->permissions()->sync($validate['permissions']);
        return redirect()->route('Roles.index')->with('success', 'Role created successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Role $Role)
    {
        if(!auth()->user()->hasPermission('permission_edit') && auth()->user()->id != "1"){
            abort(404);
        }
        $permissions = $permissions = Permission::select('model_name')->distinct()->pluck('model_name');
        return view('roles.edit',compact('Role','permissions'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Role $Role)
    {
        $validate =$request->validate([
            'name' => 'required|unique:roles,name,' . $Role->id,
            'permissions' => 'array',
        ]);
        $Role->update($validate);
        $Role->permissions()->sync($validate['permissions']);
        return redirect()->route('Roles.index')->with('success', 'Role created successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Role $Role)
    {
        $Role->delete();
        return redirect()->route('Roles.index')->with('success', 'Role deleted successfully!');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('Roles.store') }}">
            @csrf
            <div class="row">
                <div class="form-group col-md-4 mb-3">
                    <label for="name">{{__('Name')}}</label>
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autofocus>
                    @error('name')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>
            </div>

            <div class="row justify-content-center">
                <table class="table">
                    <thead class="thead-dark" style="background-color: #67c7fd !important;text-align: center">
                    <tr>
                        <th scope="col">{{__('Name')}}</th>
                        <th scope="col">{{__('Index')}}</th>
                        <th scope="col">{{__('Create')}}</th>
                        <th scope="col">{{__('Edit')}}</th>
                        <th scope="col">{{__('Delete')}}</th>
                    </tr>
                    </thead>
                    <tbody style="text-align: center">
                    @forelse($permissions as $permission)
                        <tr>
                            <th scope="row">{{__($permission)}}</th>
                            @foreach(\App\Models\Permission::where('model_name',$permission)->get() as $permission_name)
                                <td><input type="checkbox" name="permissions[]" value="{{ $permission_name->id }}"> {{--{{ $permission_name->name }}--}}</td>
                            @endforeach
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5">
                                <center>
                                    <h3>{{__('No permissions yet.')}}</h3>
                                </center>
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <button type="submit" class="btn btn-primary"><span>{{__('Create role')}}</span></button>
        </form>

    </div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('Roles.update',$Role->id) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="name">{{__('Name')}}</label>
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$Role->name) }}" required autofocus>
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

            </div>
            <div class="row justify-content-center">
                <table class="table">
                    <thead class="thead-dark" style="background-color: #67c7fd !important;text-align: center">
                        <tr>
                            <th scope="col">{{__('Name')}}</th>
                            <th scope="col">{{__('Index')}}</th>
                            <th scope="col">{{__('Create')}}</th>
                            <th scope="col">{{__('Edit')}}</th>
                            <th scope="col">{{__('Delete')}}</th>
                        </tr>
                    </thead>
                    <tbody style="text-align: center">
                        @forelse($permissions as $permission)
                            <tr>
                                <th scope="row">{{__($permission)}}</th>
                                @foreach(\App\Models\Permission::where('model_name',$permission)->get() as $permission_name)
                                    <td><input type="checkbox" @checked($Role->permissions->contains($permission_name->id) ? 'checked' : '') name="permissions[]" value="{{ $permission_name->id }}"> {{--{{ $permission_name->name }}--}}</td>
                                @endforeach
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">
                                    <center>
                                        <h3>{{__('No permissions yet.')}}</h3>
                                    </center>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <button type="submit" class="btn btn-primary"><span>{{__('Update role')}}</span></button>
        </form>

</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        @if(auth()->user()->hasPermission('permission_create') || auth()->user()->id == "1")
            <a href="{{route('Roles.create')}}" class="btn btn-primary"> <span>{{__('Create role')}}</span></a>
        @endif
        <div class="row justify-content-center">
            <table class="table">
                <thead class="thead-dark" style="background-color: #67c7fd !important;text-align: center">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">{{__('Name')}}</th>
                    <th colspan="2">{{__('Action')}}</th>
                </tr>
                </thead>
                <tbody style="text-align: center">
                @forelse($roles as $role)
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$role->name}}</td>
                    @if( auth()->user()->type == "admin")
                        <td colspan="1">
                            <center>
                                @if(auth()->user()->hasPermission('permission_edit') || auth()->user()->id == "1")
                                    <a href="{{route('Roles.edit',$role->id)}}" class="btn btn-primary"><span>{{__('Edit')}}</span></a>
                                @endif
                                @if(auth()->user()->hasPermission('permission_delete') || auth()->user()->id == "1")
                                    <form action="{{ route('Roles.destroy', $role->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-primary btn-sm"><span>{{__('Delete Role')}}</span></button>
                                    </form>
                                @endif
                            </center>
                        </td>
                    @else
                        <td colspan="2">
                            <center>
                            </center>
                        </td>
                    @endif
                </tr>
                @empty
                    <tr>
                        <td colspan="5">
                            <center>
                                <h3>{{__('No roles yet.')}}</h3>
                            </center>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection